const JSON_URL='json/book_5mvc.json';
const state={book:null,chapters:[],filtered:[],currentId:null,query:'',kind:'all',species:'all',letter:'all'};
const $=s=>document.querySelector(s);const $$=s=>Array.from(document.querySelectorAll(s));
const els={sidebar:$('#sidebar'),menuBtn:$('#menuBtn'),themeBtn:$('#themeBtn'),search:$('#searchInput'),clear:$('#clearBtn'),letters:$('#letters'),list:$('#chapterList'),count:$('#resultCount'),content:$('#content'),breadcrumbs:$('#breadcrumbs'),prev:$('#prevBtn'),next:$('#nextBtn'),copy:$('#copyBtn'),random:$('#randomBtn')};
function normalize(s=''){return String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[’‘]/g,"'").toLowerCase()}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function hl(text,q){let safe=esc(text??'');q=normalize(q).trim();if(!q||q.length<2)return safe;for(const w of q.split(/\s+/).filter(x=>x.length>1).slice(0,8)){const re=new RegExp(`(${w.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')})`,'ig');safe=safe.replace(re,'<mark>$1</mark>')}return safe}
function kindLabel(k){return{topic:'tema',appendix:'apéndice',table:'tabla',procedure:'procedimiento',index:'índice'}[k]||k||'tema'}
function chapterText(ch){const bits=[ch.title,ch.kind,ch.parent,ch.letter,...(ch.species||[]),ch.search_text,ch.plain_text];if(Array.isArray(ch.preamble))bits.push(...ch.preamble);if(Array.isArray(ch.sections)){for(const s of ch.sections){bits.push(s.title,s.heading,s.name,s.text);if(Array.isArray(s.items))bits.push(...s.items);if(Array.isArray(s.paragraphs))bits.push(...s.paragraphs);if(Array.isArray(s.subsections)){for(const sub of s.subsections){bits.push(sub.title,sub.heading,sub.name,sub.text);if(Array.isArray(sub.items))bits.push(...sub.items);if(Array.isArray(sub.paragraphs))bits.push(...sub.paragraphs)}}}}if(Array.isArray(ch.tables))bits.push(JSON.stringify(ch.tables));return normalize(bits.filter(Boolean).join(' '))}
async function loadBook(){try{const r=await fetch(JSON_URL,{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);const book=await r.json();state.book=book;state.chapters=Array.isArray(book.chapters)?book.chapters:[];state.filtered=state.chapters.slice();buildLetters();applyFilters();const first=getIdFromHash()||state.filtered[0]?.id||state.chapters[0]?.id;if(first)openChapter(first,false);if(book.meta?.content_status==='titles_only_demo')console.warn('JSON solo con títulos: al sustituirlo por el completo aparecerán secciones y texto.')}catch(e){els.content.innerHTML=`<div class="empty"><h2>No se pudo cargar el JSON</h2><p>La web busca: <code>${esc(JSON_URL)}</code></p><p>Error: <code>${esc(e.message)}</code></p><div class="info-box">En GitHub debe existir <code>json/book_5mvc.json</code>. En local usa servidor, no doble clic.</div></div>`;els.breadcrumbs.textContent='Error cargando JSON'}}
function getIdFromHash(){return decodeURIComponent(location.hash.replace(/^#/,''))||null}
function buildLetters(){const set=new Set(['all']);for(const ch of state.chapters)set.add(ch.letter||'#');const arr=[...set].sort((a,b)=>a==='all'?-1:b==='all'?1:a==='#'?-1:b==='#'?1:a.localeCompare(b));els.letters.innerHTML=arr.map(l=>`<button class="letter-btn ${l==='all'?'active':''}" data-letter="${esc(l)}">${l==='all'?'Todos':esc(l)}</button>`).join('');$$('.letter-btn').forEach(btn=>btn.onclick=()=>{state.letter=btn.dataset.letter;$$('.letter-btn').forEach(b=>b.classList.toggle('active',b===btn));applyFilters()})}
function applyFilters(){const toks=normalize(state.query).trim().split(/\s+/).filter(Boolean);state.filtered=state.chapters.filter(ch=>{if(state.kind!=='all'&&ch.kind!==state.kind)return false;if(state.species!=='all'&&!(ch.species||[]).includes(state.species))return false;if(state.letter!=='all'&&(ch.letter||'#')!==state.letter)return false;if(toks.length){const hay=chapterText(ch);if(!toks.every(t=>hay.includes(t)))return false}return true});renderList()}
function renderList(){els.count.textContent=`${state.filtered.length} resultado${state.filtered.length===1?'':'s'}`;if(!state.filtered.length){els.list.innerHTML=$('#emptyTemplate').innerHTML;return}const q=state.query;els.list.innerHTML=state.filtered.map(ch=>{const sp=(ch.species||[]).map(s=>s==='dog'?'perro':s==='cat'?'gato':s).join(', ');return `<button class="chapter-btn ${ch.id===state.currentId?'active':''}" data-id="${esc(ch.id)}"><div class="chapter-title">${hl(ch.title,q)}</div><div class="chapter-meta"><span class="badge">${esc(kindLabel(ch.kind))}</span>${sp?`<span class="badge">${esc(sp)}</span>`:''}${ch.parent?`<span class="badge">${esc(ch.parent)}</span>`:''}</div></button>`}).join('');$$('.chapter-btn').forEach(b=>b.onclick=()=>openChapter(b.dataset.id))}
function openChapter(id,pushHash=true){const ch=state.chapters.find(c=>c.id===id)||state.filtered[0]||state.chapters[0];if(!ch)return;state.currentId=ch.id;if(pushHash)history.replaceState(null,'','#'+encodeURIComponent(ch.id));renderList();renderChapter(ch);updateNavButtons();if(innerWidth<=820)els.sidebar.classList.remove('open')}
function updateNavButtons(){const i=state.filtered.findIndex(ch=>ch.id===state.currentId);els.prev.disabled=i<=0;els.next.disabled=i<0||i>=state.filtered.length-1}
function openRelative(d){const i=state.filtered.findIndex(ch=>ch.id===state.currentId);const n=state.filtered[i+d];if(n)openChapter(n.id)}
function renderChapter(ch){const meta=[`<span class="badge">${esc(kindLabel(ch.kind))}</span>`,ch.letter?`<span class="badge">Letra ${esc(ch.letter)}</span>`:'',ch.parent?`<span class="badge">${esc(ch.parent)}</span>`:'',(ch.species||[]).length?`<span class="badge">${esc((ch.species||[]).map(s=>s==='dog'?'perro':s==='cat'?'gato':s).join(', '))}</span>`:'',ch.page_start?`<span class="badge">p. ${esc(ch.page_start)}${ch.page_end?'–'+esc(ch.page_end):''}</span>`:''].filter(Boolean).join('');els.breadcrumbs.textContent=`${kindLabel(ch.kind)} / ${ch.title}`;const sections=renderSections(ch),tables=renderTables(ch.tables||[]);let body='';if(sections||tables)body=sections+tables;else if(Array.isArray(ch.preamble)&&ch.preamble.length)body=`<section class="section"><h3>Resumen</h3>${ch.preamble.map(p=>`<p>${hl(p,state.query)}</p>`).join('')}</section>`;else if(ch.plain_text&&ch.plain_text!==ch.title)body=`<section class="section"><h3>Texto</h3><div class="raw-block">${hl(ch.plain_text,state.query)}</div></section>`;else body='<div class="info-box">Este capítulo solo contiene el título en el JSON actual. Cuando sustituyas <code>json/book_5mvc.json</code> por el JSON completo generado desde el PDF, aquí aparecerán secciones clínicas, listas y tablas.</div>';els.content.innerHTML=`<header><h2>${hl(ch.title,state.query)}</h2><div class="subtitle">${meta}</div></header>${body}`}
function renderSections(ch){if(!Array.isArray(ch.sections)||!ch.sections.length)return'';return ch.sections.map(s=>{let title=s.title||s.heading||s.name||'Sección',html=`<section class="section"><h3>${esc(title)}</h3>`;if(s.text)html+=`<p>${hl(s.text,state.query)}</p>`;if(Array.isArray(s.paragraphs))html+=s.paragraphs.map(p=>`<p>${hl(p,state.query)}</p>`).join('');if(Array.isArray(s.items)&&s.items.length)html+=`<ul>${s.items.map(i=>`<li>${hl(i,state.query)}</li>`).join('')}</ul>`;if(Array.isArray(s.subsections))html+=s.subsections.map(sub=>{const t=sub.title||sub.heading||sub.name||'',pars=Array.isArray(sub.paragraphs)?sub.paragraphs:[],items=Array.isArray(sub.items)?sub.items:[];return `<div class="subsection">${t?`<h4>${esc(t)}</h4>`:''}${sub.text?`<p>${hl(sub.text,state.query)}</p>`:''}${pars.map(p=>`<p>${hl(p,state.query)}</p>`).join('')}${items.length?`<ul>${items.map(i=>`<li>${hl(i,state.query)}</li>`).join('')}</ul>`:''}</div>`}).join('');return html+'</section>'}).join('')}
function renderTables(tables){if(!Array.isArray(tables)||!tables.length)return'';return tables.map((t,i)=>{const title=t.title||`Tabla ${i+1}`,rows=t.rows||t.data||[];if(!Array.isArray(rows)||!rows.length)return `<section class="section"><h3>${esc(title)}</h3><div class="raw-block">${hl(JSON.stringify(t,null,2),state.query)}</div></section>`;const headers=t.headers||(Array.isArray(rows[0])?rows[0].map((_,j)=>`Col ${j+1}`):Object.keys(rows[0]));const body=Array.isArray(rows[0])?rows:rows.map(r=>headers.map(h=>r[h]??''));return `<section class="section"><h3>${esc(title)}</h3><div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${body.map(row=>`<tr>${row.map(c=>`<td>${hl(c,state.query)}</td>`).join('')}</tr>`).join('')}</tbody></table></div></section>`}).join('')}
function copyCurrent(){const ch=state.chapters.find(c=>c.id===state.currentId);if(!ch)return;const txt=[ch.title,'',ch.plain_text||'',...(ch.sections||[]).map(s=>[s.title||s.heading||s.name||'',s.text||'',...(s.paragraphs||[]),...(s.items||[]).map(i=>'• '+i)].filter(Boolean).join('\n'))].filter(Boolean).join('\n\n');navigator.clipboard.writeText(txt).then(()=>{const o=els.copy.textContent;els.copy.textContent='Copiado ✓';setTimeout(()=>els.copy.textContent=o,900)})}
function setupEvents(){els.search.oninput=e=>{state.query=e.target.value;applyFilters();if(state.filtered.length&&!state.filtered.some(ch=>ch.id===state.currentId))openChapter(state.filtered[0].id)};els.clear.onclick=()=>{els.search.value='';state.query='';applyFilters()};$$('[data-kind]').forEach(b=>b.onclick=()=>{state.kind=b.dataset.kind;$$('[data-kind]').forEach(x=>x.classList.toggle('active',x===b));applyFilters()});$$('[data-species]').forEach(b=>b.onclick=()=>{state.species=b.dataset.species;$$('[data-species]').forEach(x=>x.classList.toggle('active',x===b));applyFilters()});els.prev.onclick=()=>openRelative(-1);els.next.onclick=()=>openRelative(1);els.copy.onclick=copyCurrent;els.random.onclick=()=>{if(!state.filtered.length)return;openChapter(state.filtered[Math.floor(Math.random()*state.filtered.length)].id)};els.menuBtn.onclick=()=>els.sidebar.classList.toggle('open');els.themeBtn.onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('book5mvc-theme',document.body.classList.contains('light')?'light':'dark')};document.onkeydown=e=>{if(e.key==='ArrowLeft'&&!e.target.matches('input'))openRelative(-1);if(e.key==='ArrowRight'&&!e.target.matches('input'))openRelative(1);if(e.key==='/'&&!e.target.matches('input')){e.preventDefault();els.search.focus()}if(e.key==='Escape')els.sidebar.classList.remove('open')};addEventListener('hashchange',()=>{const id=getIdFromHash();if(id&&id!==state.currentId)openChapter(id,false)})}
function init(){if(localStorage.getItem('book5mvc-theme')==='light')document.body.classList.add('light');setupEvents();loadBook()}
init();
